version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"  # Backend API exposed on port 8080
    depends_on:
      - db
    environment:
      - PORT=8080
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=your_db_user
      - DATABASE_PASSWORD=your_db_password
      - DATABASE_NAME=chat_tracker
    # Removed volumes to prevent overwriting 'dist' folder
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Frontend served on port 3000
    depends_on:
      - app
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: chat_tracker
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  db-data:
